### ISSUE TITLE
apRaw duplicated in sdss_paths.ini

### ISSUE THREAD

**Issue by blanton144** [sdss/tree#9]
It looks like the latest merge into master led to a duplication of a line in sdss_paths.ini, particularly the apRaw line. This leads to an error, as below. I think that at this line needs to be removed and the Utah install needs to be updated to reflect that. 

manga.[master].172 % python
Python 3.6.3 (default, Oct 20 2017, 13:08:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdss_access.path
>>> sdss_path = sdss_access.path.Path()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/sdss_access/master/python/sdss_access/path/path.py", line 638, in __init__
    super(Path, self).__init__(pathfile, mirror=mirror, public=public, release=release, verbose=verbose)
  File "/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/sdss_access/master/python/sdss_access/path/path.py", line 61, in __init__
    self._input_templates()
  File "/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/sdss_access/master/python/sdss_access/path/path.py", line 72, in _input_templates
    foo = self._config.read([self._pathfile])
  File "/uufs/chpc.utah.edu/sys/installdir/python/3.6.3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/uufs/chpc.utah.edu/sys/installdir/python/3.6.3/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/master/data/sdss_paths.ini' [line 121]: option 'apRaw' in section 'paths' already exists
>>>

**Comment by joelbrownstein** [comment]
Hi Michael,

I removed the duplicate line from line 78 of sdss_paths.ini, and ran git pull at Utah.

`$ module switch python python/3.6.3
$ ipython
In [1]: mport sdss_access.path

In [2]: sdss_path = sdss_access.path.Path()

`

which now seems to work without the error you reported.

Cheers, Joel

**Comment by joelbrownstein** [comment]
fixed!
